src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
class Membre implements PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $mdp = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    private string $password;

    public function getPassword(): string { return $this->password;}
    public function setPassword(string $password): void {
         $this->password = $password; 
        }

    public function getRoles(): array
    {
        return ['1'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }


    public function eraseCredentials()
    {
        return $this->mdp;
    }

    public function getUserIdentifier(): string
    {
        return $this->pseudo;
    }

}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo')
            ->add('mdp', PasswordType::class)
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('civilite')
            ->add('statut')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use App\Repository\MembreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class MembreController extends AbstractController
{
    #[Route('/membre', name: 'app_membre')]
    public function index(Request $request, MembreRepository $repoMembre, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $manager): Response
    {
        $membres = $repoMembre->findAll();
        $membre = new Membre;

        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hashedPassword = $passwordHasher->hashPassword(
                $membre, 
                $membre->getMdp()
            );
            $membre->setMdp($hashedPassword);
            $membre->setDateEnregistrement(new \DateTime());
            $manager->persist($membre);
            $manager->flush();

            $this->addFlash("success", "L'membre a bien été ajoutée");

            return $this->redirectToRoute("app_membre");
        }

        return $this->render('membre/index.html.twig', [
            'controller_name' => 'Page Membre',
            'membres' => $membres,
            'formMembre' => $form->createView()
        ]);
    }
}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MembreController!
{% endblock %}

{% block body %}
	{% for notification in app.flashes('success') %}
		<div>{{ notification }}</div>
	{% endfor %}
	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Pseudo</th>
				<th scope="col">Nom</th>
				<th scope="col">Prenom</th>
				<th scope="col">Email</th>
				<th scope="col">Civilite</th>
				<th scope="col">Statut</th>
				<th scope="col">Date_Enregistrement</th>
				<th scope="col">actions</th>
			</tr>
		</thead>
		<tbody class="table-group-divider">

			{% for membre in membres %}
				<tr>
					<th scope="row">{{ membre.id }}</th>
					<td>{{ membre.pseudo }}</td>
					<td>{{ membre.nom }}</td>
					<td>{{ membre.prenom }}</td>
					<td>{{ membre.email }}</td>
					<td>{{ membre.civilite }}</td>
					<td>{{ membre.statut }}</td>
					<td>{{ membre.dateEnregistrement | date("d/m/Y") }}</td>

					<td>
						<div class="d-flex justify-content-between">
							<a href="">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#2d2d2c" class="bi bi-search" viewbox="0 0 16 16">
									<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
								</svg>
							</a>
							<a href="">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#2d2d2c" class="bi bi-pencil-square" viewbox="0 0 16 16">
									<path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
									<path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
								</svg>
							</a>
							<a href="">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#2d2d2c" class="bi bi-trash3-fill" viewbox="0 0 16 16">
									<path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
								</svg>
							</a>
						</div>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<section class="container">

		{{ form_start(formMembre)}}
		<div class="d-flex flex-column justify-content-between">
			<div class="row">
				<div class="col-md-6">
					<div class="col-md-12">
						{{ form_row(formMembre.pseudo) }}
					</div>
					<div class="col-md-12">
						{{ form_row(formMembre.mdp) }}
					</div>
					<div class="col-md-12">
						{{ form_row(formMembre.nom) }}
					</div>
					<div class="col-md-12">
						{{ form_row(formMembre.prenom) }}
					</div>
				</div>
				{# ---- #}
				<div class="col-md-6">
					<div class="col-md-12">
						{{ form_row(formMembre.email) }}
					</div>
					<div class="col-md-12">
						{{ form_row(formMembre.civilite) }}
					</div>
					<div class="col-md-12">
						{{ form_row(formMembre.statut) }}
					</div>

				</div>
				{# ---- #}
			</div>
			<div class="row">
				<button class="btn bg-primary text-light col-md-12 my-3">Valider</button>
			</div>
		</div>
		{{ form_end(formMembre)}}

	</section>

{% endblock %}